{% set name = "lunr" %}
{% set version = "0.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 3f4900fe4c12c231d6ba6a70f19e7e72883f616e4fc84ec38135230e964bdaf0
    folder: dist
  - url: https://github.com/yeraydiazdiaz/lunr.py/archive/{{ version }}.tar.gz
    sha256: 3125d17bbe966315a1a10eab8867768fbf4cb5e3efaebda8a9a9a39f7cc6861d
    folder: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
test:
  source_files:
    - src/tests
  requires:
    - mock
    - nodejs
    - pip
    - pytest
    - pytest-timeout
  imports:
    - lunr
    - lunr.builder
    - lunr.exceptions
    - lunr.field_ref
    - lunr.idf
    - lunr.index
    - lunr.languages
    - lunr.languages.stemmer
    - lunr.languages.trimmer
    - lunr.match_data
    - lunr.pipeline
    - lunr.query
    - lunr.query_lexer
    - lunr.query_parser
    - lunr.stemmer
    - lunr.stop_word_filter
    - lunr.token
    - lunr.token_set
    - lunr.token_set_builder
    - lunr.tokenizer
    - lunr.trimmer
    - lunr.utils
    - lunr.vector
  commands:
    - pip check

about:
  home: https://github.com/yeraydiazdiaz/lunr.py
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: A Python implementation of Lunr.js
  doc_url: https://lunr.readthedocs.io
  description: >
    This Python version of Lunr.js aims to bring the simple and powerful full text search capabilities into Python guaranteeing results as close as the original implementation as possible.

extra:
  recipe-maintainers:
    - bollwyvl
