{% set version = "0.8.0" %}

package:
  name: lunr
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/lunr/lunr-{{ version }}.tar.gz
  sha256: b46cf5059578d277a14bfc901bb3d5666d013bf73c035331ac0222fdac358228

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - hatch-fancy-pypi-readme >=22.8.0
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - typing-extensions
    - importlib-metadata
    - python >={{ python_min }}

test:
  source_files:
    - tests
  requires:
    - nltk
    - nodejs =18
    - pip
    - pytest-cov
    - pytest-timeout
    - python {{ python_min }}
  imports:
    - lunr
  commands:
    - pip check
    - >-
      python -c "_v_ = __import__('lunr').__VERSION__; v = __import__('importlib.metadata').metadata.version('lunr'); print(v, _v_, '{{ version }}'); assert ('{{ version }}' == _v_ == v) "
    - >-
      cd tests/acceptance_tests/javascript && npm install && cd ../.. && pytest -vv --cov=lunr --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=98

about:
  home: https://github.com/yeraydiazdiaz/lunr.py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python implementation of Lunr.js
  doc_url: https://lunr.readthedocs.io
  description: |-
    This Python version of Lunr.js aims to bring the simple and powerful full
    text search capabilities into Python guaranteeing results as close as the
    original implementation as possible.

extra:
  recipe-maintainers:
    - bollwyvl
