appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: PzCaH39xdZuX+cyX2h7n+lpc8+T4rDtJlM+CBz4Q7KmJmv0sqPPXZ18S/ZYvqLv9I0SHi6h9ojrsFYQm+H0eXDsegrsZLCcLDmkONMAabfXJWyOVGwasPudSseqe5KEpBN+BworDX73AwKrB/AbB69zflYv8/QYhkDigBvp6YhKzFX+RfiZBvhUISlS0Lsl8TjgO149peahfIWY2ROBQ61ijVIEXTPKacTCHwubfmTZNHQR9uyaktBOlv5PQlaVOcuwb/eIHwyzcQSlJI6i56mb0IiJ3QWdhSa5X06P9V7hNNw7fiJuA0H+xOByqxrt6sbDKeSfg8i1X9SAzGU0cXH34gPSosdJaB/lEiDjHAP7FJSuITE+E493oDhuG6csXmIklkBsnnKRRtVGhGTcectQ6GAS5SnwyIPqlBCL0H4ApSF56Of9GC95fEMVgnsLsrvI7gPAsSSDOGA3rC1KLzljoOWrNTbqhO/Ifk/T7XK9A66hLtHcSGszlnHbP0LtyTBpbnyOiRVLWFN+/CzbhpjxUboAVqeC5d8/Zb30sh8xL5/SDRKDyjDMF76uXOYo0z4ZxGUZv7hmtE/ceH/bF2uZgh3eBph8NHwMkyTFnxICxyyfUf5/YEkrj75UP2IQOf06+CJXslR1+LYwfjp/3l8fQEq88TBuAxK1ej89rX8o=}
provider:
  win: azure
conda_forge_output_validation: true
